name:                timestamper
version:             0.1.0.0
synopsis:            Adds a timestamp to file or directory names.
description:         Commandline utility to add a timestamp and optional text to one or more file or directory names.
homepage:            https://github.com/modul/timestamper#readme
license:             BSD3
author:              Remo Giermann
maintainer:          mo@liberejo.de
copyright:           (c) Remo Giermann
category:            Console, Filesystem, Tools
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - time
  - directory
  - filepath

executables:
  timestamper:
    source-dirs:      src
    main:             Main.hs
    dependencies:     cmdargs

tests:    
    spec: 
        main: Spec.hs
        source-dirs: [src, test]
        dependencies: [hspec, cmdargs]

