name:                addtime
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/modul/addtime#readme
license:             BSD3
author:              Remo Giermann
maintainer:          mo@liberejo.de
copyright:           (c) Remo Giermann
category:            Experimental
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - time
  - directory
  - filepath

executables:
  addtime:
    source-dirs:      src
    main:             Main.hs
